In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
path = '/home/teemo/ML/data/ex1data2.txt'
data = pd.read_csv(path,header=None, names=['Size', 'Bedrooms', 'Price'])
data.head()

Size  Bedrooms   Price
0  2104         3  399900
1  1600         3  329900
2  2400         3  369000
3  1416         2  232000
4  3000         4  539900

In [15]:
#归一化
data = (data - data.mean())/data.std()
data.head()

Size  Bedrooms     Price
0  0.130010 -0.223675  0.475747
1 -0.504190 -0.223675 -0.084074
2  0.502476 -0.223675  0.228626
3 -0.735723 -1.537767 -0.867025
4  1.257476  1.090417  1.595389

In [16]:
data.insert(0, 'Ones', 1)

In [17]:
#方差计算
def computeCost(X, y, theta):
    inner = np.power(((X * theta.T) - y), 2)
    return np.sum(inner) / (2 * len(X))

In [18]:
#梯度下降函数
def gradDescent(X, y, theta, alpha, iters):
    temp = np.matrix(np.zeros(theta.shape))
    parameters = int(theta.ravel().shape[1])
    cost = np.zeros(iters)
    
    for i in range(iters):
        error = (X * theta.T) - y
        
        for j in range(parameters):
            term = np.multiply(error, X[:,j])
            temp[0,j] = theta[0,j] - ((alpha / len(X)) * np.sum(term))
            
        theta = temp
        cost[i] = computeCost(X, y, theta)
        
    return theta, cost

In [19]:

alpha = 0.01
iters = 1500

# 初始化X和y
cols = data.shape[1]
X2 = data.iloc[:,0:cols-1]
y2 = data.iloc[:,cols-1:cols]

# 转换成matrix格式，初始化theta
X2 = np.matrix(X2.values)
y2 = np.matrix(y2.values)
theta2 = np.matrix(np.array([0,0,0]))

# 运行梯度下降算法
g2, cost2 = gradDescent(X2, y2, theta2, alpha, iters)
g2

matrix([[-1.10898288e-16,  8.84042349e-01, -5.24551809e-02]])

In [20]:
# 正规方程
def normalEqn(X, y):
    theta = np.linalg.inv(X.T@X)@X.T@y#X.T@X等价于X.T.dot(X)
    theta = np.linalg.inv(X.T@X)@X.T@y
    return theta

In [22]:
#线性回归使用正规方程可以直接算出来
final_theta2=normalEqn(X2, y2)
final_theta2

matrix([[-1.00613962e-16],
        [ 8.84765988e-01],
        [-5.31788197e-02]])